---
- name: Install php-fpm and deps 
  register: phpfpminstalled
  apt: name={{ item }} state=present
  with_items:
  - php5-fpm
  - php5-cli
  - php5-curl
  - php5-mcrypt
  - php5-memcached
  - php5-apcu
  - php5-intl
  notify:
    - Start PHP-FPM