---
- name: Install php-fpm and deps 
  register: phpfpminstalled
  apt: name={{ item }} state=present
  with_items:
  - php5-fpm
  - php5-cli
  - php5-curl
  - php5-mcrypt
  - php5-memcached
  - php5-apcu
  - php5-intl
#  - php5-xdebug
  - php5-mysql
  notify:
    - Start PHP-FPM

#- name: set config xdebug
#  template: src=xdebug.j2 dest=/etc/php5/conf.d/xdebug.ini