---
domains: [
  {
    domain: serversforhackers.com,
    document_root: /var/www,
    ssl_key: /etc/ssl/sfh/sfh.key,
    ssl_crt: /etc/ssl/sfh/sfh.crt,
    environment: production,
    index: index.php
  }
]