---
- name: Install nginx
  register: nginxinstalled
  apt: name=nginx state=present
  notify:
    - Start Nginx

- name: Add Config file
  when: nginxinstalled|success
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root
  notify:
    - Restart Nginx

- name: Disable Default Site
  when: nginxinstalled|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Add symfony Config
  when: nginxinstalled|success
  register: websiteconfig
  template: src=symfony.conf.j2 dest=/etc/nginx/sites-available/{{ item.domain }}.conf owner=root group=root
  with_items: domains

- name: Enable symfony site config
  when: websiteconfig|success
  file: src=/etc/nginx/sites-available/{{ item.domain }}.conf dest=/etc/nginx/sites-enabled/{{ item.domain }}.conf state=link
  with_items: domains
  notify:
    - Restart Nginx